# Generated by Django 4.2 on 2023-06-02 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='no bio...')),
                ('avatar', models.ImageField(default='no_picture.png', upload_to='avatars')),
                ('language', models.CharField(choices=[('English', 'English'), ('Korean', 'Korean')], default='English', max_length=12)),
                ('menubar', models.CharField(choices=[('Top', 'Top'), ('Button', 'Button')], default='Top', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('licensed_by', models.DateField(default=profiles.models.default_datetime_for_my_class)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
