# Generated by Django 4.2 on 2023-05-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='menubar',
            field=models.CharField(choices=[('Top', 'Top'), ('Button', 'Button')], default='Top', max_length=12),
        ),
    ]
