# Generated by Django 4.2 on 2023-05-21 13:10

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Korean', 'Korean')], default='English', max_length=12),
        ),
        migrations.AddField(
            model_name='profile',
            name='licensed_by',
            field=models.DateField(default=profiles.models.default_datetime_for_my_class),
        ),
        migrations.AddField(
            model_name='profile',
            name='menubar',
            field=models.CharField(choices=[('Top', 'Top'), ('Side', 'Side'), ('Bottom', 'Bottom')], default='Top', max_length=12),
        ),
    ]
