# Generated by Django 4.2 on 2023-05-12 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 19, 15, 42, 40, 636040, tzinfo=datetime.timezone.utc)),
        ),
    ]
