# Generated by Django 4.2 on 2023-06-02 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 9, 8, 38, 51, 678224, tzinfo=datetime.timezone.utc)),
        ),
    ]
