# Generated by Django 4.2 on 2023-06-02 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todoitemlist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 9, 7, 45, 59, 964488, tzinfo=datetime.timezone.utc)),
        ),
    ]
