# Generated by Django 4.2 on 2023-05-15 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todoitemlist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 11, 6, 36, 706371, tzinfo=datetime.timezone.utc)),
        ),
    ]
