# Generated by Django 4.2 on 2023-05-22 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_todoitemlist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 13, 47, 18, 676735, tzinfo=datetime.timezone.utc)),
        ),
    ]
