# Generated by Django 4.2 on 2023-05-26 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_todoitemlist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 2, 14, 18, 11, 408800, tzinfo=datetime.timezone.utc)),
        ),
    ]
