# Generated by Django 4.2 on 2023-05-27 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_todoitemlist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 3, 0, 37, 24, 63655, tzinfo=datetime.timezone.utc)),
        ),
    ]
