# Generated by Django 4.2 on 2023-05-16 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_todoitemlist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 23, 7, 18, 1, 570264, tzinfo=datetime.timezone.utc)),
        ),
    ]
