# Generated by Django 4.2 on 2023-06-03 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_todoitemlist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 14, 37, 9, 348831, tzinfo=datetime.timezone.utc)),
        ),
    ]
