# Generated by Django 4.2 on 2023-06-03 14:38

from django.db import migrations, models
import todolist.models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_todoitemlist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=todolist.models.one_week_hence),
        ),
    ]
