# Generated by Django 4.2 on 2023-05-27 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_alter_todoitemlist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitemlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 3, 7, 53, 44, 719706, tzinfo=datetime.timezone.utc)),
        ),
    ]
