# Generated by Django 4.2 on 2023-05-08 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 5, 9, 0, 10, 43, 88813))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2023, 5, 9, 0, 10, 43, 88813))),
                ('event_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
