# Generated by Django 4.2 on 2023-05-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarwithevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date']},
        ),
    ]
