# Generated by Django 4.2 on 2023-05-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarwithevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
