# Generated by Django 4.2 on 2023-05-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarwithevent', '0003_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
