# Generated by Django 4.2 on 2023-05-05 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('reports', '0004_alter_report_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
