# Generated by Django 4.2 on 2023-05-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(default='no_picture.png', upload_to='customers')),
                ('email', models.EmailField(default=None, max_length=256)),
                ('phone_number', models.CharField(default=None, max_length=265)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(default=None)),
            ],
        ),
    ]
