# Generated by Django 4.2 on 2023-05-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=265),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
