# Generated by Django 4.2 on 2023-05-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_email_alter_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='remarks',
            new_name='remark',
        ),
    ]
