# Generated by Django 4.2 on 2023-06-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_supplier_customer_updated_alter_customer_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='cc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
