# Generated by Django 4.2 on 2023-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_menubar'),
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='likers',
            field=models.ManyToManyField(related_name='post_likers', to='profiles.profile'),
        ),
    ]
