# Generated by Django 4.2 on 2023-07-03 11:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='post_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bulletin.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
