# Generated by Django 4.2 on 2023-06-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_menubar'),
        ('bulletin', '0004_alter_bulletin_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='post_likers', to='profiles.profile'),
        ),
    ]
