# Generated by Django 4.2 on 2023-06-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='inventory_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
