# Generated by Django 4.2 on 2023-06-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='delivery_completed',
            field=models.BooleanField(default=False),
        ),
    ]
