# Generated by Django 4.2 on 2023-05-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ('-created',)},
        ),
    ]
