# Generated by Django 4.2 on 2023-05-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='total_added_price',
            new_name='added_price',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='total_added_price_KRW',
            new_name='added_price_KRW',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='total_net_price',
            new_name='net_price',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='total_net_price_KRW',
            new_name='net_price_KRW',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='net_unit_price',
            new_name='unit_price',
        ),
    ]
