# Generated by Django 4.2 on 2023-05-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_position_options_alter_sale_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
