# Generated by Django 4.2 on 2023-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_position_options_alter_sale_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='added_cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='added_cost_KRW',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='ex_rate_to_KRW',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='unit_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
