# Generated by Django 4.2 on 2023-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_position_created_alter_sale_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='added_cost',
        ),
        migrations.RemoveField(
            model_name='position',
            name='added_cost_KRW',
        ),
        migrations.RemoveField(
            model_name='position',
            name='added_price',
        ),
        migrations.RemoveField(
            model_name='position',
            name='added_price_KRW',
        ),
        migrations.RemoveField(
            model_name='position',
            name='ex_rate_to_KRW',
        ),
        migrations.RemoveField(
            model_name='position',
            name='net_price_KRW',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_added_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_added_price_KRW',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_net_price_KRW',
        ),
        migrations.AddField(
            model_name='position',
            name='inventory_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='margin_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='net_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='extra_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='final_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='net_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
