# Generated by Django 4.2 on 2023-05-05 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0002_remove_csv_activated_csv_csv_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
