# Generated by Django 4.2 on 2023-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_position_added_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='delivery_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='extra_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vat_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
