# Generated by Django 4.2 on 2023-05-05 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0003_alter_position_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
