# Generated by Django 4.2 on 2023-07-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_position_margin_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='final_profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_net_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_net_profit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
