# Generated by Django 4.2 on 2023-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_position_added_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
    ]
