# Generated by Django 4.2 on 2023-06-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_delivery_cost_alter_sale_extra_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='net_profit',
            new_name='total_net_profit',
        ),
    ]
