# Generated by Django 4.2 on 2023-06-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_net_profit_sale_total_net_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_sold',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
