# Generated by Django 4.2 on 2023-06-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
