# Generated by Django 4.2 on 2023-06-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_unit_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
