# Generated by Django 4.2 on 2023-06-06 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 6, 20, 27, 17, 311187)),
        ),
    ]
