# Generated by Django 4.2 on 2023-07-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_average_ex_rate_to_krw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remark',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
