# Generated by Django 4.2 on 2023-06-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_supplier_customer_updated_alter_customer_created'),
        ('products', '0007_alter_product_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('KRW', 'South Korean Won'), ('BTC', 'Bitcoin'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('GBP', 'British Pound Sterling')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='product_customers', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='moq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_quantity_base',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_supplier', to='customers.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
