# Generated by Django 4.2 on 2023-06-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_cc_supplier_cc'),
        ('products', '0008_product_currency_product_customers_product_moq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_supplier', to='customers.supplier'),
        ),
    ]
