# Generated by Django 4.2 on 2023-06-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='moq',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
