# Generated by Django 4.2 on 2023-06-13 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_moq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('net_price', models.FloatField()),
                ('added_cost', models.FloatField(default=0)),
                ('added_price', models.FloatField()),
                ('ex_rate_to_KRW', models.FloatField()),
                ('custom_tax_KRW', models.FloatField(default=0)),
                ('transport_cost_KRW', models.FloatField(default=0)),
                ('bank_cost_KRW', models.FloatField(default=0)),
                ('delivery_cost_KRW', models.FloatField(default=0)),
                ('net_price_KRW', models.FloatField()),
                ('added_price_KRW', models.FloatField()),
                ('status', models.CharField(choices=[('prep', 'Preparation'), ('PO', 'PO issued'), ('Invoice', 'Invoice paid'), ('Arrived', 'Arrived'), ('Stocked', 'Stocked')], max_length=30)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_purchase', to='products.product')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
