# Generated by Django 4.2 on 2023-06-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_inventory_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_ex_rate_to_KRW',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='average_unit_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_added_price_KRW',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_net_price_KRW',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.FloatField(default=0, null=True),
        ),
    ]
