# Generated by Django 4.2 on 2023-06-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_average_ex_rate_to_krw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_quantity_base',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
