# Generated by Django 4.2 on 2023-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_price_quantity_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='average_unit_price',
            new_name='average_unit_price_KRW',
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
